In [1]:
#Numpy Assignment Questions


#Q1. What is a Python library? Why do we use Python libraries?

Python Library:

A Python library is a collection of related modules. It contains bundles of code that can be used repeatedly in different programs.

It makes Python Programming simpler and convenient for the programmer.

As we don’t need to write the same code again and again for different programs.

Python libraries play a very vital role in fields of Machine Learning, Data Science, Data Visualization, etc.

The following are among the most important:
    1. Pandas
    
    2. NumPy
    
    3. Keras
    
    4. TensorFlow

    5. Scikit Learn

    6. Eli5

    7. SciPy

    8. PyTorch

    9. LightGBM

    10. Theano

Use Python libraries

As we write large-size programs in Python, we want to maintain the code’s modularity.

For the easy maintenance of the code, we split the code into different parts and we can use that code later ever we need it.

In Python, modules play that part. Instead of using the same code in different programs and making the code complex, we define mostly used functions in modules and we can just simply import them in a program wherever there is a requirement. 

We don’t need to write that code but still, we can use its functionality by importing its module. 

Multiple interrelated modules are stored in a library. And whenever we need to use a module, we import it from its library.

#Q2. What is the difference between Numpy array and List?

Python Lists:

The list can be homogeneous or heterogeneous.

Element-wise operation is not possible on the list.

Python list is by default 1-dimensional. But we can create an N-Dimensional list. 

But then too it will be 1 D list storing another 1D list

Elements of a list need not be contiguous in memory.

Numpy arrays:

We can create an N-dimensional array in Python using Numpy.array().

The array is by default Homogeneous, which means data inside an array must be of the same Datatype. (Note You can also create a structured array in Python).

Element-wise operation is possible.

Numpy array has various functions, methods, and variables, to ease our task of matrix computation.

Elements of an array are stored contiguously in memory. For example, all rows of a two-dimensioned array must have the same number of columns.

A three-dimensional array must have the same number of rows and columns on each card.

In [4]:
"""
Q3. Find the shape, size and dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]
"""


import numpy as np
arr=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
shape=arr.shape
size=arr.size
dimension=arr.ndim
print("Shape of array :",shape)
print("Size of array :",size)
print("Dimension of array :",dimension)

Shape of array : (3, 4)
Size of array : 12
Dimension of array : 2


We create and intialize array called array using the numpy.array() function.

Now by the help of functions like shape ,size & ndim we will find the shape, size and dimension of the array.

By the print function we should print that and program ends

In [6]:
"""
4. Write python code to access the first row of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]
"""


import numpy as np

array = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
first_row = array[0]
print("First row of the following array : ",first_row)

First row of the following array :  [1 2 3 4]


We create and intialize array called array using the numpy.array() function.

We then access the first row of the array using the array[0] syntax.

Finally, we print the first row using the print() function.

In [8]:
"""
5. How do you access the element at the third row and fourth column from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]
"""

import numpy as np

array = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
third__fourth_row_column = array[0]
print("Third row and fourth column from the given numpy array : ",third__fourth_row_column) 

Third row and fourth column from the given numpy array :  [1 2 3 4]


We create and intialize array called array using the numpy.array() function.

We then access the first row of the array using the array[3][4] syntax.

Finally, we print the same using the print() function.


In [16]:
"""
6. Write code to extract all odd-indexed elements from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]
"""
import numpy as np
array = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
odd_elements = array[1::2]
print(odd_elements)

[[5 6 7 8]]


We create and intialize array called array using the numpy.array() function.

Now with the help of indexing and slicing we will find the odd index element.

Finally, we print the same using the print() function.

In [8]:
#Q7. How can you generate a random 3x3 matrix with values between 0 and 1?


import numpy as np
matrix = np.random.rand(3, 3)
print(matrix)

[[0.17440445 0.20645191 0.30619681]
 [0.05778717 0.65091675 0.24165404]
 [0.61912841 0.33014573 0.92816934]]


We create and intialize array called array using the numpy.array() function.

Now by the help of function like np.random.rand we will generate a random 3x3 matrix with values between 0 and 1.

By the print function we should print that and program ends

#Q8. Describe the difference numpy.random.rand() vs numpy.random.random()?





The numpy.random.rand() generates random values in a given shape. 

It creates an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

On the other hand, numpy.random.random() return random floats in the half-open interval [0.0, 1.0).

Both functions generate samples from the uniform distribution on [0, 1). 

The only difference is in how the arguments are handled.

With numpy.random.rand(), the length of each dimension of the output array is a separate argument. 
                                                                  
With numpy.random.random_sample(), the shape argument is a single tuple.

Let us understand with the help of an example,

In [7]:
import numpy as np
print("values using rand:\n",np.random.rand(3, 5),"\n")

print("Values using random:\n",np.random.random_sample((3, 5)),"\n")

values using rand:
 [[0.5001389  0.46833587 0.35242362 0.46420501 0.33191494]
 [0.01894991 0.80619123 0.71777365 0.02712717 0.14362703]
 [0.47993636 0.32318477 0.89967747 0.03398681 0.57410792]] 

Values using random:
 [[0.96918186 0.17491059 0.79378846 0.24908548 0.80586175]
 [0.48967999 0.26915449 0.80279314 0.74118796 0.94339023]
 [0.69087978 0.41462311 0.77480795 0.33917479 0.16389503]] 



In [15]:
"""
9. Write code to increase the dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]
"""
import numpy as np
a = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print("Dimension before expansion :",a.ndim)
b=np.expand_dims(a,axis=2)
print("Dimension after expansion :",b.ndim)

Dimension before expansion : 2
Dimension after expansion : 3


We create and intialize array called array using the numpy.array() function.

Now by the help of function np.expand_dims we will increase the dimension of the array.

In [2]:
"""
#Q10. How to transpose the following array in NumPy?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]
"""
import numpy as np

array = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
array.transpose()

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

We create and intialize array called array using the numpy.array() function.

The transpose() function takes an array as input and returns a new array with the rows and columns swapped

In [9]:
"""
11. Consider the following matrix:

Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Perform the following operation using Python1
Index wise multiplication'
Matrix multiplication'
Add both the matrix
Subtract matrix B from A
Divide matrix B by A
"""
import numpy as np
import numpy.matlib 

A= np.array([[1, 2, 3,4],[5, 6, 7,8],[9, 10, 11,12]])

B =np.array([[1, 2, 3,4],[5, 6, 7,8],[9, 10, 11,12]])

print("Index wise multiplication :","\n",np.multiply(A,B))
print("Matrix multiplication :","\n",np.matmul((A.T),B))
print("Add both the matrix : ","\n",np.add(A,B))
print("Subtract matrix B from A :","\n",np.subtract(A,B))
print("Subtract matrix B from A : ","\n",np.divide(B,A))

Index wise multiplication : 
 [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
Matrix multiplication : 
 [[107 122 137 152]
 [122 140 158 176]
 [137 158 179 200]
 [152 176 200 224]]
Add both the matrix :  
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
Subtract matrix B from A : 
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Subtract matrix B from A :  
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


We create and intialize both array called A & B using the numpy.array() function.

Now by using functions like np.multiply,np.matmul,np.add,np.subtract,np.divide find the followings
                      
                      Index wise multiplication
                      
                      Matrix multiplication
                      
                      Add both the matrix
                      
                      Subtract matrix B from A
                      
                      Divide matrix B by A

Finally, we print the above using the print() function.


#Q12.  Which function in Numpy can be used to swap the byte order of an array?


The byteswap() function in NumPy can be used to swap the byte order of an array.

The function takes an array as input and returns a new array with the bytes swapped.

The function can also be used to swap the bytes of an array in-place.

Here is an example of how to use the byteswap() function:

In [1]:
import numpy as np
array = np.array([1, 2, 3, 4, 5])
swapped_array = array.byteswap()
print(swapped_array)

[ 72057594037927936 144115188075855872 216172782113783808
 288230376151711744 360287970189639680]


#Q13  What is the significance of the np.linalg.inv function?

The np.linalg.inv function in Python is used to compute the inverse of a matrix.

The inverse of a matrix is a matrix that, when multiplied by the original matrix, results in the identity matrix. 

The identity matrix is a square matrix with 1's on the diagonal and 0's everywhere else.

The np.linalg.inv function can be used to solve systems of linear equations, to find the inverse of a transformation matrix, and to compute other matrix operations.

Here is an example of how to use the np.linalg.inv function:

In [2]:
import numpy as np
A = np.array([[1, 2], [3, 4]])
A_inv = np.linalg.inv(A)
print(A_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


#Q14.What does the np.reshape function do, and how is it used?

The . reshape() function rearranges the data in an ndarray into a new shape. 

The new shape must be compatible with the old one, though an index of -1 can be used to infer one dimension.

For example, if you have an array with shape (4,3) and you want to reshape it to shape (6,2), you would use the following code:

In [4]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6],[7,8,9],[10,11,12]])
new_arr = arr.reshape(6,2)

print(new_arr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


#15. What is broadcasting in Numpy?


The term broadcasting refers to the ability of NumPy to treat arrays of different shapes during arithmetic operations. 

Arithmetic operations on arrays are usually done on corresponding elements. 

If two arrays are of exactly the same shape, then these operations are smoothly performed.

Here is an example:

In [6]:
import numpy as np 

a = np.array([1,2,3,4]) 
b = np.array([10,20,30,40]) 
c = a * b 
print (c)

[ 10  40  90 160]
